### ISSUE TITLE
Changing include_extras default to 'false'

### ISSUE THREAD

**Issue by bsipocz** [astropy/conda-build-tools#19]
@mwcraig - think this idea would make sense and potentially would save us from future troubles, but don't want to open a PR before hearing your preference. 

https://github.com/astropy/conda-channel-astropy/pull/62#issuecomment-235872497

> My feeling is that include_extras: false would be the better default, so that packages can be installed with minimal dependencies, and then packages could opt-in to include_extras: true.
> But of course, @mwcraig and @bsipocz - whatever you as maintainers prefer is the right solution.

**Comment by mwcraig** [comment]
Yes, I agree.
