### ISSUE TITLE
Extend extruder to keep two channels in sync

### ISSUE THREAD

**Issue by astrofrog** [astropy/conda-build-tools#25]
For glue, I wanted to have a script that will sync all versions of the glue builds to the glueviz channel, so I wrote the following script:

https://gist.github.com/astrofrog/7542ac898aff74b80e3b6501edddc327

Maybe this could be somehow incorporated into extruder?

**Comment by astrofrog** [comment]
Here's the script in action: https://github.com/glue-viz/conda-sync

I'd be tempted to combine this with ``copy_packages`` here and we could release it as a standalone thing as it could be quite useful generically?

**Comment by mwcraig** [comment]
Sorry, @astrofrog, I completely missed the comment here. 

I agree that combining the scripts and releasing would be useful. 

Still interested?

**Comment by astrofrog** [comment]
I'm interested in trying to help, but I'm going to be on vacation for two of the coming three weeks, so unfortunately it won't happen until September.

**Comment by mwcraig** [comment]
Will you be at the coordination meeting? That might be a good time...in any event I have plenty to keep me busy until September.

**Comment by astrofrog** [comment]
Yep, I'll be there!
