### ISSUE TITLE
Copying post releases is not working

### ISSUE THREAD

**Issue by bsipocz** [astropy/conda-build-tools#26]
astroquery is build on conda-forge, and thus we copy it over to astropy. The latest release needed to get a post patch due to licence issues. However this post release is now not picked up for copying over to the other channel.

**Comment by mwcraig** [comment]
Will take a look...

**Comment by mwcraig** [comment]
Looks like the new copy infrastructure will pick it up; will see in astropy/conda-channel-astropy#157
